name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Or 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow the GitHub Actions bot to push to the repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install
          npm install styled-components
          npm install react-router-dom

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Set up GitHub token for authentication
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Build the app
        run: npm run build

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
